# Generated by Django 6.1.1 on 2026-10-05 15:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#2563eb', max_length=20, verbose_name='Cor Identificadora')),
                ('icon', models.CharField(default='layers', max_length=50, verbose_name='Ícone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razão Social / Nome')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=25, verbose_name='CNPJ / CPF')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Pessoa de Contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='SKU / Código Único')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Código de Barras (EAN)')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Produto')),
                ('unit_measure', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Peça'), ('KG', 'Quilograma'), ('MT', 'Metro'), ('LT', 'Litro'), ('PAR', 'Par'), ('KIT', 'Kit')], default='UN', max_length=10, verbose_name='Unidade')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço de Custo (R$)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço de Venda (R$)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('max_stock', models.IntegerField(default=200, verbose_name='Estoque Máximo')),
                ('location', models.CharField(blank=True, default='Setor A - Estante 1', max_length=120, verbose_name='Localização no Depósito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='Categoria')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier', verbose_name='Fornecedor Principal')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Estoque Baixo'), ('OUT_OF_STOCK', 'Ruptura Total (Esgotado)')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada (+ Inventário)'), ('OUT', 'Saída (- Inventário)'), ('ADJUST', 'Ajuste / Balanço Físico')], max_length=10, verbose_name='Tipo de Movimento')),
                ('quantity', models.IntegerField(verbose_name='Quantidade Movimentada')),
                ('previous_stock', models.IntegerField(verbose_name='Estoque Anterior')),
                ('new_stock', models.IntegerField(verbose_name='Novo Estoque')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Unitário')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo / Finalidade')),
                ('reference_doc', models.CharField(blank=True, max_length=120, null=True, verbose_name='Doc / NF / Pedido')),
                ('performed_by', models.CharField(default='Administrador', max_length=120, verbose_name='Responsável')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
