# Generated by Django 6.1.1 on 2026-10-07 15:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do Arquivamento'),
        ),
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Arquivamento'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Arquivado'),
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Destinatário')),
                ('recipient_address', models.CharField(max_length=300, verbose_name='Endereço de Entrega')),
                ('recipient_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone de Contato')),
                ('carrier', models.CharField(choices=[('CORREIOS', 'Correios'), ('LOGGI', 'Loggi'), ('MELHOR_ENVIO', 'Melhor Envio'), ('JADLOG', 'Jadlog'), ('EXPRESS', 'Entrega Expressa Direta')], default='CORREIOS', max_length=50, verbose_name='Transportadora')),
                ('tracking_code', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Código de Rastreamento')),
                ('external_delivery_url', models.URLField(blank=True, max_length=500, verbose_name='Link no Site de Entregas')),
                ('status', models.CharField(choices=[('PREPARING', 'Em Preparação'), ('DISPATCHED', 'Despachado'), ('IN_TRANSIT', 'Em Trânsito'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PREPARING', max_length=30, verbose_name='Status da Entrega')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do Frete (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Instruções de Despacho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Ordem de Entrega',
                'verbose_name_plural': 'Ordens de Entrega',
                'ordering': ['-created_at'],
            },
        ),
    ]
